ViewModels/EmployeeEditCreateModel.cs
using DotNetCoreFunda.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreFunda.ViewModels
{
    public class EmployeeEditCreateModel
    {
        [Required, Display(Name = "Employee Name"), MaxLength(50)]
        public string Name { get; set; }
        public EmployeeType EmpType { get; set; }
    }
}

ViewModels/HomeIndexViewModel.cs
using DotNetCoreFunda.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreFunda.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Employee> Employees { get; set; }
        public string TasksForToday { get; set; }
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreFunda.Controllers
{
    [Route("[controller]/[action]")]
    public class AboutController
    {
        public string Index()
        {
            return "Index method";
        }

        public string OfficeAddress()
        {
            return "Complete Office Address - Lorem Ipsum";
        }

        public string HomeAddress()
        {
            return "Complete Home Address - Lorem Ipsum";
        }
    }
}

Controllers/HomeController.cs
using DotNetCoreFunda.Model;
using DotNetCoreFunda.Services;
using DotNetCoreFunda.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreFunda.Controllers
{
    public class HomeController : Controller
    {
        private IEmployeeData _employeeData;
        private IGreeter _greeter;

        public HomeController(IEmployeeData employeeData, IGreeter greeter)
        {
            _employeeData = employeeData;
            _greeter = greeter;
        }
        public ActionResult Index()
        {
            //var model = new Employee() { Id = 1, Name = "Anurag" };
            //return Content("Hello from HomeController's Index method!");
            //return View(_employeeData.GetAll());
            var viewmodel = new HomeIndexViewModel()
            {
                Employees = _employeeData.GetAll(),
                TasksForToday = _greeter.GetMessage()
            };
            return View(viewmodel);
        }

        public IActionResult Details(int id)
        {
            var model = _employeeData.Get(id);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeEditCreateModel emp)
        {
            if (ModelState.IsValid) {
                var newEmp = new Employee();
                newEmp.Name = emp.Name;
                newEmp.EmployeeType = emp.EmpType;
                newEmp = _employeeData.Add(newEmp);

                //return View("Details", newEmp);
                return RedirectToAction(nameof(Details), new { id = newEmp.Id });
            }
            else
            {
                return View();  
            }
        }
    }
}

Pages/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DotNetCoreFunda.Services;
using DotNetCoreFunda.Model;

namespace DotNetCoreFunda.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeeData dataService;
        [BindProperty]
        public Employee Employee { get; set; }
        public EditModel(IEmployeeData dataService)
        {
            this.dataService = dataService;
        }
        public IActionResult OnGet(int id )
        {
            Employee = dataService.Get(id);
            if (Employee == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                Employee = dataService.Update(Employee);
                return RedirectToAction("Details", "Home", new {id = Employee.Id });
            }
            return Page();

        }
    }
}

Pages/Welcome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DotNetCoreFunda.Services;

namespace DotNetCoreFunda.Pages
{
    public class WelcomeModel : PageModel
    {
        private readonly IGreeter _greeter;
        public string GreetingMessage { get; set; }
        public WelcomeModel(IGreeter greeter)
        {
            this._greeter = greeter;
        }
        public void OnGet(string name)
        {
            GreetingMessage = $"{name} : {_greeter.GetMessage()}";
        }
    }
}

ViewComponents/WelcomeViewComponent.cs
using DotNetCoreFunda.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreFunda.ViewComponents
{
    public class WelcomeViewComponent : ViewComponent
    {
        private readonly IGreeter greeter;

        public WelcomeViewComponent(IGreeter greeter)
        {
            this.greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = greeter.GetMessage();
            //this will be like View("viewName") as it just contains a string.
            //return View(model);
            return View("Default", model);
        }
    }
}

Pages/Employees/Edit.cshtml
@page "{id}"
@using DotNetCoreFunda.Pages.Employees


@model EditModel
<h1>Edit @Model.Employee.Name:</h1>
<form method="post">
    <input type="hidden" asp-for="Employee.Id"/>
    @*<input type="text" name="Name" value="" />*@
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Employee.Name"></label>
        <input asp-for="Employee.Name" />
        <span asp-validation-for="Employee.Name"></span>
    </div>
    <div>
        <label asp-for="Employee.EmployeeType"></label>
        <select asp-for="Employee.EmployeeType" asp-items="Html.GetEnumSelectList<Employee.EmployeeType>()"></select>
        <span asp-validation-for="Employee.EmployeeType"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

Pages/Welcome.cshtml
@page "{name}"

@model WelcomeModel
<div>
    @Model.GreetingMessage
</div>

Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
    </footer>
</body>
</html>

Views/Home/Create.cshtml
@using DotNetCoreFunda.Model
@model  Employee;

<h1>Create:</h1>
<form method="post">
    @*<input type="text" name="Name" value="" />*@
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="EmployeeType"></label>
        <select asp-for="EmployeeType" asp-items="@Html.GetEnumSelectList<EmployeeType>()"></select>
        <span asp-validation-for="EmployeeType"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

Views/Home/Details.cshtml
@model DotNetCoreFunda.Model.Employee;
<h2>Details</h2>
<div>@Model.Id</div>
<div>@Model.Name</div>
<a asp-action="Index" asp-controller="Home">Home</a>
<

Views/Home/Index.cshtml
@*@model IEnumerable<DotNetCoreFunda.Model.Employee>;*@
@model DotNetCoreFunda.ViewModels.HomeIndexViewModel;
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <div>Task for today: @Model.TasksForToday</div>
    <h1>All Employees</h1>

    @foreach (var emp in Model.Employees)
    {
        @Html.Partial("_Summary", emp)
    }
    <a asp-action="Create">Create an employee:</a>
</body>
</html>

Views/Home/_Summary.cshtml
@model Employee

    <section>
        <h2>@Model.Name</h2>
        <div>Emp type: @Model.EmployeeType</div>
         <div>
             <a asp-action="Details" asp-route-id="@Model.Id">More</a>
             <a asp-page="/Employees/Edit" asp-route-id="@Model.Id">Edit</a>
         </div>
    </section>

Views/Shared/Components/Welcome/Default.cshtml
@model string 

<div>@Model</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        Footer:
        @RenderSection("footer", required:false)
        @*@await Component.InvokeAsync("Welcome")*@
        <vc:welcome></vc:welcome>
    </footer>
</body>
</html>